export const SET_COORD = 'SET_COORD'
export const SET_ZOOM = 'SET_ZOOM'
export const SET_STYLE = 'SET_STYLE'
export const NEED_ADDRESS_START = 'NEED_ADDRESS_START'
export const NEED_ADDRESS_END = 'NEED_ADDRESS_END'
export const NEED_ADDRESS_FAIL = 'NEED_ADDRESS_FAIL'
export const USE_MILLIGRATICULE = 'USE_MILLIGRATICULE'
export const SET_POPUP_STATUS = 'SET_POPUP_STATUS'

export const URL_MAP = 'map'
export const URL_STYLE = 'style'
export const URL_GEOHASH = 'geohash'
export const URL_ZOOM = 'zoom'
export const URL_GOOGLE = 'google'
export const URL_FORMAT = 'url'
export const URL_HUMAN = 'human'
