/* eslint-disable */
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var latlonparser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,9],$V1=[1,10],$V2=[1,8],$V3=[1,25],$V4=[1,28],$V5=[1,26],$V6=[1,27],$V7=[1,29],$V8=[1,30],$V9=[5,8,11,12,13,15,17,19,20,22,23,25,26,27],$Va=[5,8,11,12,13],$Vb=[11,12,13,20,22,23,25,26],$Vc=[20,22,23,25,26];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"expression":3,"coord":4,"EOF":5,"lat":6,"lon":7,"SEP":8,"number":9,"float":10,"EFLOAT":11,"FFLOAT":12,"INTEGER":13,"degreevalue":14,"DEGREE":15,"minutevalue":16,"MINUTE":17,"secondvalue":18,"SECOND":19,"SOUTH_OR_SECOND":20,"latdir":21,"NORTH":22,"SOUTH":23,"londir":24,"EAST":25,"WEST":26,"HOURSEP":27,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:"SEP",11:"EFLOAT",12:"FFLOAT",13:"INTEGER",15:"DEGREE",17:"MINUTE",19:"SECOND",20:"SOUTH_OR_SECOND",22:"NORTH",23:"SOUTH",25:"EAST",26:"WEST",27:"HOURSEP"},
productions_: [0,[3,2],[4,2],[4,3],[4,2],[4,3],[4,2],[4,3],[10,1],[10,1],[9,1],[9,1],[14,2],[16,2],[18,2],[18,2],[21,1],[21,1],[21,1],[24,1],[24,1],[6,4],[6,3],[6,2],[6,6],[6,4],[6,2],[7,4],[7,3],[7,2],[7,6],[7,4],[7,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

            return $$[$0-1]
        
break;
case 2:
 this.$ = createCoord($$[$0-1],$$[$0]) 
break;
case 3:
 this.$ = createCoord($$[$0-2],$$[$0]) 
break;
case 4:
 this.$ = createCoord($$[$0],$$[$0-1]) 
break;
case 5:
 this.$ = createCoord($$[$0],$$[$0-2]) 
break;
case 6:
 this.$ = createCoord(createLat(createDegree($$[$0-1]),0,0,1),createLon(createDegree($$[$0]),0,0,1)) 
break;
case 7:
 this.$ = createCoord(createLat(createDegree($$[$0-2]),0,0,1),createLon(createDegree($$[$0]),0,0,1)) 
break;
case 8:
 this.$ = createEFloat(yytext) 
break;
case 9:
 this.$ = createFFloat(yytext) 
break;
case 10:
 this.$ = $$[$0] 
break;
case 11:
 this.$ = createInteger(yytext) 
break;
case 12:
 this.$ = createDegree($$[$0-1]) 
break;
case 13:
 this.$ = createMinute($$[$0-1]) 
break;
case 14: case 15:
 this.$ = createSecond($$[$0-1]) 
break;
case 16: case 19:
 this.$ = 1 
break;
case 17: case 18: case 20:
 this.$ = -1 
break;
case 21:
 this.$ = createLat($$[$0-3],$$[$0-2],$$[$0-1],$$[$0]) 
break;
case 22:
 this.$ = createLat($$[$0-2],$$[$0-1],0,$$[$0]) 
break;
case 23:
 this.$ = createLat($$[$0-1],0,0,$$[$0]) 
break;
case 24:
 this.$ = createLat(createDegree($$[$0-5]),createMinute($$[$0-3]),createSecond($$[$0-1]),$$[$0]) 
break;
case 25:
 this.$ = createLat(createDegree($$[$0-3]),createMinute($$[$0-1]),0,$$[$0]) 
break;
case 26:
 this.$ = createLat(createDegree($$[$0-1]),0,0, $$[$0]) 
break;
case 27:
 this.$ = createLon($$[$0-3],$$[$0-2],$$[$0-1],$$[$0]) 
break;
case 28:
 this.$ = createLon($$[$0-2],$$[$0-1],0,$$[$0]) 
break;
case 29:
 this.$ = createLon($$[$0-1],0,0,$$[$0]) 
break;
case 30:
 this.$ = createLon(createDegree($$[$0-5]),createMinute($$[$0-3]),createSecond($$[$0-1]),$$[$0]) 
break;
case 31:
 this.$ = createLon(createDegree($$[$0-3]),createMinute($$[$0-1]),0,$$[$0]) 
break;
case 32:
 this.$ = createLon(createDegree($$[$0-1]),0,0,$$[$0]) 
break;
}
},
table: [{3:1,4:2,6:3,7:4,9:5,10:7,11:$V0,12:$V1,13:$V2,14:6},{1:[3]},{5:[1,11]},{7:12,8:[1,13],9:15,10:7,11:$V0,12:$V1,13:$V2,14:14},{6:16,8:[1,17],9:19,10:7,11:$V0,12:$V1,13:$V2,14:18},{8:[1,21],9:20,10:7,11:$V0,12:$V1,13:$V2,15:$V3,20:$V4,21:23,22:$V5,23:$V6,24:24,25:$V7,26:$V8,27:[1,22]},{9:34,10:7,11:$V0,12:$V1,13:$V2,16:31,20:$V4,21:32,22:$V5,23:$V6,24:33,25:$V7,26:$V8},o($V9,[2,10]),o($V9,[2,11]),o($V9,[2,8]),o($V9,[2,9]),{1:[2,1]},{5:[2,2]},{7:35,9:15,10:7,11:$V0,12:$V1,13:$V2,14:14},{9:34,10:7,11:$V0,12:$V1,13:$V2,16:36,24:33,25:$V7,26:$V8},{15:$V3,24:24,25:$V7,26:$V8,27:[1,37]},{5:[2,4]},{6:38,9:19,10:7,11:$V0,12:$V1,13:$V2,14:18},{9:34,10:7,11:$V0,12:$V1,13:$V2,16:39,20:$V4,21:32,22:$V5,23:$V6},{15:$V3,20:$V4,21:23,22:$V5,23:$V6,27:[1,40]},{5:[2,6]},{9:41,10:7,11:$V0,12:$V1,13:$V2},{9:42,10:7,11:$V0,12:$V1,13:$V2},o($Va,[2,26]),o($Va,[2,32]),o($Vb,[2,12]),o($Va,[2,16]),o($Va,[2,17]),o($Va,[2,18]),o($Va,[2,19]),o($Va,[2,20]),{9:46,10:7,11:$V0,12:$V1,13:$V2,18:43,20:$V4,21:44,22:$V5,23:$V6,24:45,25:$V7,26:$V8},o($Va,[2,23]),o($Va,[2,29]),{17:[1,47]},{5:[2,3]},{9:46,10:7,11:$V0,12:$V1,13:$V2,18:48,24:45,25:$V7,26:$V8},{9:49,10:7,11:$V0,12:$V1,13:$V2},{5:[2,5]},{9:46,10:7,11:$V0,12:$V1,13:$V2,18:50,20:$V4,21:44,22:$V5,23:$V6},{9:51,10:7,11:$V0,12:$V1,13:$V2},{5:[2,7]},{20:$V4,21:53,22:$V5,23:$V6,24:54,25:$V7,26:$V8,27:[1,52]},{20:$V4,21:55,22:$V5,23:$V6,24:56,25:$V7,26:$V8},o($Va,[2,22]),o($Va,[2,28]),{19:[1,57],20:[1,58]},o($Vb,[2,13]),{24:56,25:$V7,26:$V8},{24:54,25:$V7,26:$V8,27:[1,59]},{20:$V4,21:55,22:$V5,23:$V6},{20:$V4,21:53,22:$V5,23:$V6,27:[1,60]},{9:61,10:7,11:$V0,12:$V1,13:$V2},o($Va,[2,25]),o($Va,[2,31]),o($Va,[2,21]),o($Va,[2,27]),o($Vc,[2,14]),o($Vc,[2,15]),{9:62,10:7,11:$V0,12:$V1,13:$V2},{9:63,10:7,11:$V0,12:$V1,13:$V2},{20:$V4,21:64,22:$V5,23:$V6,24:65,25:$V7,26:$V8},{24:65,25:$V7,26:$V8},{20:$V4,21:64,22:$V5,23:$V6},o($Va,[2,24]),o($Va,[2,30])],
defaultActions: {11:[2,1],12:[2,2],16:[2,4],20:[2,6],35:[2,3],38:[2,5],41:[2,7]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

const {createEFloat, createFFloat, createInteger, createDegree, createMinute, createSecond, createLat, createLon, createCoord} = require('./objects.js')
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:
break;
case 1:
break;
case 2:
break;
case 3:return 8
break;
case 4:return 8
break;
case 5:return 11
break;
case 6:return 12
break;
case 7:return 13
break;
case 8:return 8
break;
case 9:return 8
break;
case 10:return 22
break;
case 11:return 22
break;
case 12:return 22
break;
case 13:return 22
break;
case 14:return 25
break;
case 15:return 25
break;
case 16:return 25
break;
case 17:return 25
break;
case 18:return 26
break;
case 19:return 26
break;
case 20:return 26
break;
case 21:return 26
break;
case 22:return 23
break;
case 23:return 23
break;
case 24:return 23
break;
case 25:return 23
break;
case 26:return 15
break;
case 27:return 17
break;
case 28:return 19
break;
case 29:return 22
break;
case 30:return 25
break;
case 31:return 26
break;
case 32:return 23
break;
case 33:return 20
break;
case 34:return 27
break;
case 35:return 8
break;
case 36:return 5
break;
case 37:return 'INVALID'
break;
}
},
rules: [/^(?:\n)/,/^(?:\s+)/,/^(?:\t)/,/^(?:\/)/,/^(?:;)/,/^(?:-?[0-9]+\.[0-9]+)/,/^(?:-?[0-9]+,[0-9]+)/,/^(?:-?[0-9]+)/,/^(?:,)/,/^(?:-)/,/^(?:North\b)/,/^(?:north\b)/,/^(?:Nord\b)/,/^(?:nord\b)/,/^(?:East\b)/,/^(?:east\b)/,/^(?:Est\b)/,/^(?:est\b)/,/^(?:West\b)/,/^(?:west\b)/,/^(?:Ouest\b)/,/^(?:ouest\b)/,/^(?:South\b)/,/^(?:south\b)/,/^(?:Sud\b)/,/^(?:sud\b)/,/^(?:[°hd])/,/^(?:[’′'m])/,/^(?:[”″\"])/,/^(?:[Nn])/,/^(?:[Ee])/,/^(?:[OWow])/,/^(?:[S])/,/^(?:s\b)/,/^(?::)/,/^(?:,)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();
export default latlonparser;
